# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProductCodeFolder.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_D_NewPCFolder(object):
    def setupUi(self, D_NewPCFolder):
        D_NewPCFolder.setObjectName("D_NewPCFolder")
        D_NewPCFolder.resize(658, 208)
        self.groupBox_productCode = QtWidgets.QGroupBox(D_NewPCFolder)
        self.groupBox_productCode.setGeometry(QtCore.QRect(10, 10, 631, 151))
        self.groupBox_productCode.setObjectName("groupBox_productCode")
        self.tableWidget_ProductCode = QtWidgets.QTableWidget(self.groupBox_productCode)
        self.tableWidget_ProductCode.setGeometry(QtCore.QRect(210, 10, 411, 131))
        self.tableWidget_ProductCode.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_ProductCode.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_ProductCode.setObjectName("tableWidget_ProductCode")
        self.tableWidget_ProductCode.setColumnCount(4)
        self.tableWidget_ProductCode.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setHorizontalHeaderItem(3, item)
        self.label_productCode = QtWidgets.QLabel(self.groupBox_productCode)
        self.label_productCode.setGeometry(QtCore.QRect(11, 29, 69, 16))
        self.label_productCode.setObjectName("label_productCode")
        self.label_printingType = QtWidgets.QLabel(self.groupBox_productCode)
        self.label_printingType.setGeometry(QtCore.QRect(10, 60, 67, 16))
        self.label_printingType.setObjectName("label_printingType")
        self.widget = QtWidgets.QWidget(self.groupBox_productCode)
        self.widget.setGeometry(QtCore.QRect(10, 90, 191, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_add = QtWidgets.QPushButton(self.widget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_2.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(self.widget)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_2.addWidget(self.pushButton_remove)
        self.widget1 = QtWidgets.QWidget(self.groupBox_productCode)
        self.widget1.setGeometry(QtCore.QRect(92, 29, 111, 48))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_productCode = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_productCode.setObjectName("lineEdit_productCode")
        self.verticalLayout_2.addWidget(self.lineEdit_productCode)
        self.comboBox_printingType = QtWidgets.QComboBox(self.widget1)
        self.comboBox_printingType.setObjectName("comboBox_printingType")
        self.comboBox_printingType.addItem("")
        self.comboBox_printingType.addItem("")
        self.comboBox_printingType.addItem("")
        self.comboBox_printingType.addItem("")
        self.comboBox_printingType.addItem("")
        self.comboBox_printingType.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_printingType)
        self.widget2 = QtWidgets.QWidget(D_NewPCFolder)
        self.widget2.setGeometry(QtCore.QRect(490, 170, 158, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_create = QtWidgets.QPushButton(self.widget2)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout.addWidget(self.pushButton_create)
        self.pushButton_close = QtWidgets.QPushButton(self.widget2)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)

        self.retranslateUi(D_NewPCFolder)
        QtCore.QMetaObject.connectSlotsByName(D_NewPCFolder)

        self.pushButton_add.clicked.connect(self.addProductCode)
        self.pushButton_close.clicked.connect(QtWidgets.qApp.quit)

    def retranslateUi(self, D_NewPCFolder):
        _translate = QtCore.QCoreApplication.translate
        D_NewPCFolder.setWindowTitle(_translate("D_NewPCFolder", "New Product Code Folder"))
        self.groupBox_productCode.setTitle(_translate("D_NewPCFolder", "Product Code Information"))
        item = self.tableWidget_ProductCode.horizontalHeaderItem(0)
        item.setText(_translate("D_NewPCFolder", "Product Code"))
        item = self.tableWidget_ProductCode.horizontalHeaderItem(1)
        item.setText(_translate("D_NewPCFolder", "Printing Type"))
        item = self.tableWidget_ProductCode.horizontalHeaderItem(2)
        item.setText(_translate("D_NewPCFolder", "Sub-Program"))
        item = self.tableWidget_ProductCode.horizontalHeaderItem(3)
        item.setText(_translate("D_NewPCFolder", "LOGO"))
        self.label_productCode.setText(_translate("D_NewPCFolder", "Product Code:"))
        self.label_printingType.setText(_translate("D_NewPCFolder", "Printing Type:"))
        self.pushButton_add.setText(_translate("D_NewPCFolder", "Add"))
        self.pushButton_remove.setText(_translate("D_NewPCFolder", "Remove"))
        self.comboBox_printingType.setItemText(0, _translate("D_NewPCFolder", "<Select type>"))
        self.comboBox_printingType.setItemText(1, _translate("D_NewPCFolder", "Arc_Thermal"))
        self.comboBox_printingType.setItemText(2, _translate("D_NewPCFolder", "Digital"))
        self.comboBox_printingType.setItemText(3, _translate("D_NewPCFolder", "Offset"))
        self.comboBox_printingType.setItemText(4, _translate("D_NewPCFolder", "PFL"))
        self.comboBox_printingType.setItemText(5, _translate("D_NewPCFolder", "Woven"))
        self.pushButton_create.setText(_translate("D_NewPCFolder", "Create"))
        self.pushButton_close.setText(_translate("D_NewPCFolder", "Close"))

    def addProductCode(self):
        rowPosition = self.tableWidget_ProductCode.rowCount()
        productCode = self.lineEdit_productCode.text()
        printing_type = self.comboBox_printingType.currentText()
        checkBox_subProgram = QtWidgets.QCheckBox()
        checkBox_logo = QtWidgets.QCheckBox()
        self.tableWidget_ProductCode.insertRow(rowPosition)
        item = QtWidgets.QTableWidgetItem(productCode)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setItem(rowPosition, 0, item)
        item = QtWidgets.QTableWidgetItem(printing_type)
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_ProductCode.setItem(rowPosition, 1, item)
        # item = QtWidgets.QTableWidgetItem(checkBox_subProgram)
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget_ProductCode.setItem(rowPosition, 2, item)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_D_NewPCFolder()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
